// Default language chains, ported from the original single-file version.
// `order` determines the bridge/scheduling chain sequence (lower = earlier).

export function defaultMamaLanguages() {
  const L = (key, name, flag, level, bridge, diff, order, status = 'todo', note = '') => ({
    key, name, flag, level, bridge, diff, order, status, note, chain: true, fromLevel: null, removable: false,
  });
  return [
    L('english', 'Английский', '🇬🇧', 'B2', null, 1.00, 1, 'learning', 'база — с неё начинаем'),
    L('swedish', 'Шведский', '🇸🇪', 'B2', 'english', 0.75, 2, 'learning', 'германская семья, как английский'),
    L('arabic', 'Арабский', '🕌', 'C1', null, 1.70, 3, 'learning', 'уже учите — для Корана'),
    L('turkish', 'Турецкий', '🇹🇷', 'B1', 'arabic', 1.30, 4, 'todo', 'много арабских слов в турецком'),
    L('chinese', 'Китайский', '🇨🇳', 'B1', null, 1.70, 5, 'todo', 'новая ветка — тона + иероглифы, самый сложный старт'),
    L('korean', 'Корейский', '🇰🇷', 'B1', 'chinese', 1.30, 6, 'todo', '~60% корейских слов — китайские заимствования'),
    L('japanese', 'Японский', '🇯🇵', 'B1', 'korean', 1.10, 7, 'todo', 'двойной мост: грамматика как в корейском + кандзи как в китайском'),
  ];
}

export function defaultKausarLanguages() {
  const L = (key, name, flag, level, bridge, diff, order, status, note, fromLevel = null) => ({
    key, name, flag, level, bridge, diff, order, status, note, chain: true, fromLevel, removable: false,
  });
  return [
    L('english', 'Английский', '🇬🇧', 'C2', null, 1.00, 1, 'learning', 'уже на уровне B1, продолжаем до C2', 'B1'),
    L('swedish', 'Шведский', '🇸🇪', 'B1', 'english', 0.75, 2, 'todo', 'германская семья, как английский'),
    L('french', 'Французский', '🇫🇷', 'B1', 'english', 1.15, 3, 'todo', 'много общей лексики с английским'),
    L('arabic', 'Арабский', '🕌', 'C2', null, 1.70, 4, 'todo', 'новая ветка — алфавит с нуля'),
    L('turkish', 'Турецкий', '🇹🇷', 'B1', 'arabic', 1.30, 5, 'todo', 'много арабских слов в турецком'),
    L('hindi', 'Хинди', '🇮🇳', 'B1', 'arabic', 1.55, 6, 'todo', 'лексика пересекается через урду/фарси/арабский'),
    L('chinese', 'Китайский', '🇨🇳', 'B1', null, 1.70, 7, 'todo', 'новая ветка — тона + иероглифы, самый сложный старт'),
    L('korean', 'Корейский', '🇰🇷', 'B1', 'chinese', 1.30, 8, 'todo', '~60% корейских слов — китайские заимствования'),
    L('japanese', 'Японский', '🇯🇵', 'B1', 'korean', 1.10, 9, 'todo', 'двойной мост: грамматика как в корейском + кандзи как в китайском'),
  ];
}

export function defaultLanguagesFor(ownerId) {
  return ownerId === 'kausar' ? defaultKausarLanguages() : defaultMamaLanguages();
}

export function defaultMamaBooks() {
  return [
    { title: 'Джаваб. Исчерпывающий ответ', author: 'Ибн аль-Каййим', language: 'Русский', pages: 560, genre: 'religion', order: 1 },
  ];
}

export function defaultKausarBooks() {
  return [
    { title: 'The 100', author: 'Kass Morgan', language: 'Английский', pages: 325, difficulty: 'B1', genre: 'dystopia', order: 1 },
    { title: 'Day 21', author: 'Kass Morgan', language: 'Английский', pages: 336, difficulty: 'B1', genre: 'dystopia', order: 2 },
    { title: 'Homecoming', author: 'Kass Morgan', language: 'Английский', pages: 352, difficulty: 'B1', genre: 'dystopia', order: 3 },
    { title: 'Rebellion', author: 'Kass Morgan', language: 'Английский', pages: 368, difficulty: 'B1', genre: 'dystopia', order: 4 },
    { title: 'The Maze Runner', author: 'James Dashner', language: 'Английский', pages: 375, difficulty: 'B1', genre: 'dystopia', order: 5 },
    { title: 'The Scorch Trials', author: 'James Dashner', language: 'Английский', pages: 360, difficulty: 'B1', genre: 'dystopia', order: 6 },
    { title: 'The Death Cure', author: 'James Dashner', language: 'Английский', pages: 325, difficulty: 'B1', genre: 'dystopia', order: 7 },
    { title: 'The Kill Order', author: 'James Dashner', language: 'Английский', pages: 370, difficulty: 'B1', genre: 'dystopia', order: 8 },
    { title: 'The Fever Code', author: 'James Dashner', language: 'Английский', pages: 380, difficulty: 'B1', genre: 'dystopia', order: 9 },
    { title: 'Crank Palace', author: 'James Dashner', language: 'Английский', pages: 130, difficulty: 'B1', genre: 'dystopia', order: 10 },
    { title: 'The Maze Cutter', author: 'James Dashner', language: 'Английский', pages: 325, difficulty: 'B1', genre: 'dystopia', order: 11 },
    { title: 'The Godhead Complex', author: 'James Dashner', language: 'Английский', pages: 272, difficulty: 'B1', genre: 'dystopia', order: 12 },
    { title: 'The Hunger Games', author: 'Suzanne Collins', language: 'Английский', pages: 374, difficulty: 'B1+', genre: 'dystopia', order: 13 },
    { title: 'Catching Fire', author: 'Suzanne Collins', language: 'Английский', pages: 391, difficulty: 'B1+', genre: 'dystopia', order: 14 },
    { title: 'Mockingjay', author: 'Suzanne Collins', language: 'Английский', pages: 390, difficulty: 'B1+', genre: 'dystopia', order: 15 },
    { title: 'The Ballad of Songbirds and Snakes', author: 'Suzanne Collins', language: 'Английский', pages: 517, difficulty: 'B1+', genre: 'dystopia', order: 16 },
    { title: 'Sunrise on the Reaping', author: 'Suzanne Collins', language: 'Английский', pages: 400, difficulty: 'B1+', genre: 'dystopia', order: 17 },
    { title: 'The Selection', author: 'Kiera Cass', language: 'Английский', pages: 327, difficulty: 'B1+', genre: 'romance', order: 18 },
    { title: 'The Elite', author: 'Kiera Cass', language: 'Английский', pages: 323, difficulty: 'B1+', genre: 'romance', order: 19 },
    { title: 'The One', author: 'Kiera Cass', language: 'Английский', pages: 323, difficulty: 'B1+', genre: 'romance', order: 20 },
    { title: 'The Heir', author: 'Kiera Cass', language: 'Английский', pages: 342, difficulty: 'B1+', genre: 'romance', order: 21 },
    { title: 'The Crown', author: 'Kiera Cass', language: 'Английский', pages: 278, difficulty: 'B1+', genre: 'romance', order: 22 },
    { title: 'The Lightning Thief', author: 'Rick Riordan', language: 'Английский', pages: 377, difficulty: 'B1+', genre: 'fantasy', order: 23 },
    { title: 'The Sea of Monsters', author: 'Rick Riordan', language: 'Английский', pages: 279, difficulty: 'B1+', genre: 'fantasy', order: 24 },
    { title: 'The Titan\'s Curse', author: 'Rick Riordan', language: 'Английский', pages: 312, difficulty: 'B1+', genre: 'fantasy', order: 25 },
    { title: 'The Battle of the Labyrinth', author: 'Rick Riordan', language: 'Английский', pages: 361, difficulty: 'B1+', genre: 'fantasy', order: 26 },
    { title: 'The Last Olympian', author: 'Rick Riordan', language: 'Английский', pages: 381, difficulty: 'B1+', genre: 'fantasy', order: 27 },
    { title: 'The Naturals', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 336, difficulty: 'B1+', genre: 'thriller', order: 28 },
    { title: 'Killer Instinct', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 336, difficulty: 'B1+', genre: 'thriller', order: 29 },
    { title: 'All In', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 352, difficulty: 'B1+', genre: 'thriller', order: 30 },
    { title: 'Bad Blood', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 352, difficulty: 'B1+', genre: 'thriller', order: 31 },
    { title: 'All Systems Red', author: 'Martha Wells', language: 'Английский', pages: 144, difficulty: 'B1+', genre: 'scifi', order: 32 },
    { title: 'Artificial Condition', author: 'Martha Wells', language: 'Английский', pages: 160, difficulty: 'B1+', genre: 'scifi', order: 33 },
    { title: 'Rogue Protocol', author: 'Martha Wells', language: 'Английский', pages: 160, difficulty: 'B1+', genre: 'scifi', order: 34 },
    { title: 'Exit Strategy', author: 'Martha Wells', language: 'Английский', pages: 176, difficulty: 'B1+', genre: 'scifi', order: 35 },
    { title: 'Network Effect', author: 'Martha Wells', language: 'Английский', pages: 352, difficulty: 'B1+', genre: 'scifi', order: 36 },
    { title: 'Fugitive Telemetry', author: 'Martha Wells', language: 'Английский', pages: 176, difficulty: 'B1+', genre: 'scifi', order: 37 },
    { title: 'System Collapse', author: 'Martha Wells', language: 'Английский', pages: 245, difficulty: 'B1+', genre: 'scifi', order: 38 },
    { title: 'Divergent', author: 'Veronica Roth', language: 'Английский', pages: 487, difficulty: 'B2', genre: 'dystopia', order: 39 },
    { title: 'Insurgent', author: 'Veronica Roth', language: 'Английский', pages: 525, difficulty: 'B2', genre: 'dystopia', order: 40 },
    { title: 'Allegiant', author: 'Veronica Roth', language: 'Английский', pages: 526, difficulty: 'B2', genre: 'dystopia', order: 41 },
    { title: 'Four', author: 'Veronica Roth', language: 'Английский', pages: 302, difficulty: 'B2', genre: 'dystopia', order: 42 },
    { title: 'A Court of Thorns and Roses', author: 'Sarah J. Maas', language: 'Английский', pages: 419, difficulty: 'B2', genre: 'fantasy', order: 43 },
    { title: 'A Court of Mist and Fury', author: 'Sarah J. Maas', language: 'Английский', pages: 624, difficulty: 'B2', genre: 'fantasy', order: 44 },
    { title: 'A Court of Wings and Ruin', author: 'Sarah J. Maas', language: 'Английский', pages: 699, difficulty: 'B2', genre: 'fantasy', order: 45 },
    { title: 'A Court of Frost and Starlight', author: 'Sarah J. Maas', language: 'Английский', pages: 288, difficulty: 'B2', genre: 'fantasy', order: 46 },
    { title: 'A Court of Silver Flames', author: 'Sarah J. Maas', language: 'Английский', pages: 757, difficulty: 'B2', genre: 'fantasy', order: 47 },
    { title: 'Storm Front', author: 'Jim Butcher', language: 'Английский', pages: 322, difficulty: 'B2', genre: 'fantasy', order: 48 },
    { title: 'Fool Moon', author: 'Jim Butcher', language: 'Английский', pages: 367, difficulty: 'B2', genre: 'fantasy', order: 49 },
    { title: 'Grave Peril', author: 'Jim Butcher', language: 'Английский', pages: 421, difficulty: 'B2', genre: 'fantasy', order: 50 },
    { title: 'Summer Knight', author: 'Jim Butcher', language: 'Английский', pages: 405, difficulty: 'B2', genre: 'fantasy', order: 51 },
    { title: 'Death Masks', author: 'Jim Butcher', language: 'Английский', pages: 449, difficulty: 'B2', genre: 'fantasy', order: 52 },
    { title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', language: 'Английский', pages: 465, difficulty: 'B2', genre: 'thriller', order: 53 },
    { title: 'The Girl Who Played with Fire', author: 'Stieg Larsson', language: 'Английский', pages: 503, difficulty: 'B2', genre: 'thriller', order: 54 },
    { title: 'The Girl Who Kicked the Hornets\' Nest', author: 'Stieg Larsson', language: 'Английский', pages: 563, difficulty: 'B2', genre: 'thriller', order: 55 },
    { title: 'The Girl in the Spider\'s Web', author: 'David Lagercrantz', language: 'Английский', pages: 400, difficulty: 'B2', genre: 'thriller', order: 56 },
    { title: 'The Girl Who Takes an Eye for an Eye', author: 'David Lagercrantz', language: 'Английский', pages: 496, difficulty: 'B2', genre: 'thriller', order: 57 },
    { title: 'The Girl Who Lived Twice', author: 'David Lagercrantz', language: 'Английский', pages: 384, difficulty: 'B2', genre: 'thriller', order: 58 },
    { title: 'The Girl in the Eagle\'s Talons', author: 'Karin Smirnoff', language: 'Английский', pages: 352, difficulty: 'B2', genre: 'thriller', order: 59 },
    { title: 'Red Rising', author: 'Pierce Brown', language: 'Английский', pages: 382, difficulty: 'B2', genre: 'scifi', order: 60 },
    { title: 'Golden Son', author: 'Pierce Brown', language: 'Английский', pages: 443, difficulty: 'B2', genre: 'scifi', order: 61 },
    { title: 'Morning Star', author: 'Pierce Brown', language: 'Английский', pages: 517, difficulty: 'B2', genre: 'scifi', order: 62 },
    { title: 'Iron Gold', author: 'Pierce Brown', language: 'Английский', pages: 596, difficulty: 'B2', genre: 'scifi', order: 63 },
    { title: 'Dark Age', author: 'Pierce Brown', language: 'Английский', pages: 704, difficulty: 'B2', genre: 'scifi', order: 64 },
    { title: 'Light Bringer', author: 'Pierce Brown', language: 'Английский', pages: 704, difficulty: 'B2', genre: 'scifi', order: 65 },
    { title: 'A Study in Scarlet', author: 'Arthur Conan Doyle', language: 'Английский', pages: 154, difficulty: 'B2+', genre: 'detective', order: 66 },
    { title: 'The Sign of Four', author: 'Arthur Conan Doyle', language: 'Английский', pages: 180, difficulty: 'B2+', genre: 'detective', order: 67 },
    { title: 'The Hound of the Baskervilles', author: 'Arthur Conan Doyle', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 68 },
    { title: 'The Valley of Fear', author: 'Arthur Conan Doyle', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 69 },
    { title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', language: 'Английский', pages: 307, difficulty: 'B2+', genre: 'detective', order: 70 },
    { title: 'The Memoirs of Sherlock Holmes', author: 'Arthur Conan Doyle', language: 'Английский', pages: 280, difficulty: 'B2+', genre: 'detective', order: 71 },
    { title: 'The Return of Sherlock Holmes', author: 'Arthur Conan Doyle', language: 'Английский', pages: 320, difficulty: 'B2+', genre: 'detective', order: 72 },
    { title: 'The Mysterious Affair at Styles', author: 'Agatha Christie', language: 'Английский', pages: 296, difficulty: 'B2+', genre: 'detective', order: 73 },
    { title: 'The Murder of Roger Ackroyd', author: 'Agatha Christie', language: 'Английский', pages: 288, difficulty: 'B2+', genre: 'detective', order: 74 },
    { title: 'Murder on the Orient Express', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 75 },
    { title: 'Death on the Nile', author: 'Agatha Christie', language: 'Английский', pages: 288, difficulty: 'B2+', genre: 'detective', order: 76 },
    { title: 'Cards on the Table', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 77 },
    { title: 'Five Little Pigs', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 78 },
    { title: 'Evil Under the Sun', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 79 },
    { title: 'Curtain', author: 'Agatha Christie', language: 'Английский', pages: 240, difficulty: 'B2+', genre: 'detective', order: 80 },
    { title: 'The Fellowship of the Ring', author: 'J. R. R. Tolkien', language: 'Английский', pages: 423, difficulty: 'B2+', genre: 'fantasy', order: 81 },
    { title: 'The Two Towers', author: 'J. R. R. Tolkien', language: 'Английский', pages: 352, difficulty: 'B2+', genre: 'fantasy', order: 82 },
    { title: 'The Return of the King', author: 'J. R. R. Tolkien', language: 'Английский', pages: 416, difficulty: 'B2+', genre: 'fantasy', order: 83 },
    { title: 'Leviathan Wakes', author: 'James S. A. Corey', language: 'Английский', pages: 561, difficulty: 'B2+', genre: 'scifi', order: 84 },
    { title: 'Caliban\'s War', author: 'James S. A. Corey', language: 'Английский', pages: 595, difficulty: 'B2+', genre: 'scifi', order: 85 },
    { title: 'Abaddon\'s Gate', author: 'James S. A. Corey', language: 'Английский', pages: 539, difficulty: 'B2+', genre: 'scifi', order: 86 },
    { title: 'Wool', author: 'Hugh Howey', language: 'Английский', pages: 571, difficulty: 'B2+', genre: 'dystopia', order: 87 },
    { title: 'Shift', author: 'Hugh Howey', language: 'Английский', pages: 594, difficulty: 'B2+', genre: 'dystopia', order: 88 },
    { title: 'Dust', author: 'Hugh Howey', language: 'Английский', pages: 386, difficulty: 'B2+', genre: 'dystopia', order: 89 },
    { title: 'Guards! Guards!', author: 'Terry Pratchett', language: 'Английский', pages: 288, difficulty: 'C1', genre: 'fantasy', order: 90 },
    { title: 'Men at Arms', author: 'Terry Pratchett', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 91 },
    { title: 'Feet of Clay', author: 'Terry Pratchett', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 92 },
    { title: 'Jingo', author: 'Terry Pratchett', language: 'Английский', pages: 384, difficulty: 'C1', genre: 'fantasy', order: 93 },
    { title: 'The Fifth Elephant', author: 'Terry Pratchett', language: 'Английский', pages: 384, difficulty: 'C1', genre: 'fantasy', order: 94 },
    { title: 'Night Watch', author: 'Terry Pratchett', language: 'Английский', pages: 352, difficulty: 'C1', genre: 'fantasy', order: 95 },
    { title: 'Thud!', author: 'Terry Pratchett', language: 'Английский', pages: 384, difficulty: 'C1', genre: 'fantasy', order: 96 },
    { title: 'Snuff', author: 'Terry Pratchett', language: 'Английский', pages: 400, difficulty: 'C1', genre: 'fantasy', order: 97 },
    { title: 'Neverwhere', author: 'Neil Gaiman', language: 'Английский', pages: 370, difficulty: 'C1', genre: 'fantasy', order: 98 },
    { title: 'Stardust', author: 'Neil Gaiman', language: 'Английский', pages: 256, difficulty: 'C1', genre: 'fantasy', order: 99 },
    { title: 'American Gods', author: 'Neil Gaiman', language: 'Английский', pages: 588, difficulty: 'C1', genre: 'fantasy', order: 100 },
    { title: 'Anansi Boys', author: 'Neil Gaiman', language: 'Английский', pages: 336, difficulty: 'C1', genre: 'fantasy', order: 101 },
    { title: 'The Ocean at the End of the Lane', author: 'Neil Gaiman', language: 'Английский', pages: 181, difficulty: 'C1', genre: 'fantasy', order: 102 },
    { title: 'The Eyre Affair', author: 'Jasper Fforde', language: 'Английский', pages: 374, difficulty: 'C1', genre: 'detective', order: 103 },
    { title: 'Lost in a Good Book', author: 'Jasper Fforde', language: 'Английский', pages: 399, difficulty: 'C1', genre: 'detective', order: 104 },
    { title: 'The Well of Lost Plots', author: 'Jasper Fforde', language: 'Английский', pages: 388, difficulty: 'C1', genre: 'detective', order: 105 },
    { title: 'Something Rotten', author: 'Jasper Fforde', language: 'Английский', pages: 394, difficulty: 'C1', genre: 'detective', order: 106 },
    { title: 'First Among Sequels', author: 'Jasper Fforde', language: 'Английский', pages: 366, difficulty: 'C1', genre: 'detective', order: 107 },
    { title: 'One of Our Thursdays Is Missing', author: 'Jasper Fforde', language: 'Английский', pages: 356, difficulty: 'C1', genre: 'detective', order: 108 },
    { title: 'The Woman Who Died a Lot', author: 'Jasper Fforde', language: 'Английский', pages: 356, difficulty: 'C1', genre: 'detective', order: 109 },
    { title: 'Rivers of London', author: 'Ben Aaronovitch', language: 'Английский', pages: 400, difficulty: 'C1', genre: 'fantasy', order: 110 },
    { title: 'Moon Over Soho', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 111 },
    { title: 'Whispers Under Ground', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 112 },
    { title: 'Broken Homes', author: 'Ben Aaronovitch', language: 'Английский', pages: 336, difficulty: 'C1', genre: 'fantasy', order: 113 },
    { title: 'Foxglove Summer', author: 'Ben Aaronovitch', language: 'Английский', pages: 352, difficulty: 'C1', genre: 'fantasy', order: 114 },
    { title: 'The Hanging Tree', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 115 },
    { title: 'Lies Sleeping', author: 'Ben Aaronovitch', language: 'Английский', pages: 400, difficulty: 'C1', genre: 'fantasy', order: 116 },
    { title: 'False Value', author: 'Ben Aaronovitch', language: 'Английский', pages: 368, difficulty: 'C1', genre: 'fantasy', order: 117 },
    { title: 'Amongst Our Weapons', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 118 },
    { title: '1984', author: 'George Orwell', language: 'Английский', pages: 328, difficulty: 'C2', genre: 'dystopia', order: 119 },
    { title: 'Brave New World', author: 'Aldous Huxley', language: 'Английский', pages: 288, difficulty: 'C2', genre: 'dystopia', order: 120 },
    { title: 'The Handmaid\'s Tale', author: 'Margaret Atwood', language: 'Английский', pages: 311, difficulty: 'C2', genre: 'dystopia', order: 121 },
    { title: 'Never Let Me Go', author: 'Kazuo Ishiguro', language: 'Английский', pages: 288, difficulty: 'C2', genre: 'drama', order: 122 },
    { title: 'Jonathan Strange & Mr Norrell', author: 'Susanna Clarke', language: 'Английский', pages: 782, difficulty: 'C2', genre: 'fantasy', order: 123 },
    { title: 'Wolf Hall', author: 'Hilary Mantel', language: 'Английский', pages: 653, difficulty: 'C2', genre: 'classic', order: 124 },
  ];
}

export function defaultBooksFor(ownerId) {
  return ownerId === 'kausar' ? defaultKausarBooks() : defaultMamaBooks();
}
