// Default language chains, ported from the original single-file version.
// `order` determines the bridge/scheduling chain sequence (lower = earlier).

export function defaultMamaLanguages() {
  const L = (key, name, flag, level, bridge, diff, order, status = 'todo', note = '') => ({
    key, name, flag, level, bridge, diff, order, status, note, chain: true, fromLevel: null, removable: false,
  });
  return [
    L('english', 'Английский', '🇬🇧', 'B2', null, 1.00, 1, 'learning', 'база — с неё начинаем'),
    L('swedish', 'Шведский', '🇸🇪', 'B2', 'english', 0.75, 2, 'learning', 'германская семья, как английский'),
    L('arabic', 'Арабский', '🕌', 'C1', null, 1.70, 3, 'learning', 'уже учите — для Корана'),
    L('turkish', 'Турецкий', '🇹🇷', 'B1', 'arabic', 1.30, 4, 'todo', 'много арабских слов в турецком'),
    L('chinese', 'Китайский', '🇨🇳', 'B1', null, 1.70, 5, 'todo', 'новая ветка — тона + иероглифы, самый сложный старт'),
    L('korean', 'Корейский', '🇰🇷', 'B1', 'chinese', 1.30, 6, 'todo', '~60% корейских слов — китайские заимствования'),
    L('japanese', 'Японский', '🇯🇵', 'B1', 'korean', 1.10, 7, 'todo', 'двойной мост: грамматика как в корейском + кандзи как в китайском'),
  ];
}

export function defaultKausarLanguages() {
  const L = (key, name, flag, level, bridge, diff, order, status, note, fromLevel = null) => ({
    key, name, flag, level, bridge, diff, order, status, note, chain: true, fromLevel, removable: false,
  });
  return [
    L('english', 'Английский', '🇬🇧', 'C2', null, 1.00, 1, 'learning', 'уже на уровне B1, продолжаем до C2', 'B1'),
    L('swedish', 'Шведский', '🇸🇪', 'B1', 'english', 0.75, 2, 'todo', 'германская семья, как английский'),
    L('french', 'Французский', '🇫🇷', 'B1', 'english', 1.15, 3, 'todo', 'много общей лексики с английским'),
    L('arabic', 'Арабский', '🕌', 'C2', null, 1.70, 4, 'todo', 'новая ветка — алфавит с нуля'),
    L('turkish', 'Турецкий', '🇹🇷', 'B1', 'arabic', 1.30, 5, 'todo', 'много арабских слов в турецком'),
    L('hindi', 'Хинди', '🇮🇳', 'B1', 'arabic', 1.55, 6, 'todo', 'лексика пересекается через урду/фарси/арабский'),
    L('chinese', 'Китайский', '🇨🇳', 'B1', null, 1.70, 7, 'todo', 'новая ветка — тона + иероглифы, самый сложный старт'),
    L('korean', 'Корейский', '🇰🇷', 'B1', 'chinese', 1.30, 8, 'todo', '~60% корейских слов — китайские заимствования'),
    L('japanese', 'Японский', '🇯🇵', 'B1', 'korean', 1.10, 9, 'todo', 'двойной мост: грамматика как в корейском + кандзи как в китайском'),
  ];
}

export function defaultLanguagesFor(ownerId) {
  return ownerId === 'kausar' ? defaultKausarLanguages() : defaultMamaLanguages();
}

export function defaultMamaBooks() {
  return [
    { title: 'Джаваб. Исчерпывающий ответ', author: 'Ибн аль-Каййим', language: 'Русский', pages: 560, genre: 'religion', order: 1 },
  ];
}

export function defaultKausarBooks() {
  return [
    { title: 'The 100', author: 'Kass Morgan', language: 'Английский', pages: 325, difficulty: 'B1', genre: 'dystopia', order: 1 },
    { title: 'Day 21', author: 'Kass Morgan', language: 'Английский', pages: 336, difficulty: 'B1', genre: 'dystopia', order: 2 },
    { title: 'Homecoming', author: 'Kass Morgan', language: 'Английский', pages: 352, difficulty: 'B1', genre: 'dystopia', order: 3 },
    { title: 'Rebellion', author: 'Kass Morgan', language: 'Английский', pages: 368, difficulty: 'B1', genre: 'dystopia', order: 4 },
    { title: 'The Maze Runner', author: 'James Dashner', language: 'Английский', pages: 375, difficulty: 'B1', genre: 'dystopia', order: 5 },
    { title: 'The Scorch Trials', author: 'James Dashner', language: 'Английский', pages: 360, difficulty: 'B1', genre: 'dystopia', order: 6 },
    { title: 'The Death Cure', author: 'James Dashner', language: 'Английский', pages: 325, difficulty: 'B1', genre: 'dystopia', order: 7 },
    { title: 'The Kill Order', author: 'James Dashner', language: 'Английский', pages: 370, difficulty: 'B1', genre: 'dystopia', order: 8 },
    { title: 'The Fever Code', author: 'James Dashner', language: 'Английский', pages: 380, difficulty: 'B1', genre: 'dystopia', order: 9 },
    { title: 'Crank Palace', author: 'James Dashner', language: 'Английский', pages: 130, difficulty: 'B1', genre: 'dystopia', order: 10 },
    { title: 'The Maze Cutter', author: 'James Dashner', language: 'Английский', pages: 325, difficulty: 'B1', genre: 'dystopia', order: 11 },
    { title: 'The Godhead Complex', author: 'James Dashner', language: 'Английский', pages: 272, difficulty: 'B1', genre: 'dystopia', order: 12 },
    { title: 'The Hunger Games', author: 'Suzanne Collins', language: 'Английский', pages: 374, difficulty: 'B1+', genre: 'dystopia', order: 13 },
    { title: 'Catching Fire', author: 'Suzanne Collins', language: 'Английский', pages: 391, difficulty: 'B1+', genre: 'dystopia', order: 14 },
    { title: 'Mockingjay', author: 'Suzanne Collins', language: 'Английский', pages: 390, difficulty: 'B1+', genre: 'dystopia', order: 15 },
    { title: 'The Ballad of Songbirds and Snakes', author: 'Suzanne Collins', language: 'Английский', pages: 517, difficulty: 'B1+', genre: 'dystopia', order: 16 },
    { title: 'Sunrise on the Reaping', author: 'Suzanne Collins', language: 'Английский', pages: 400, difficulty: 'B1+', genre: 'dystopia', order: 17 },
    { title: 'The Selection', author: 'Kiera Cass', language: 'Английский', pages: 327, difficulty: 'B1+', genre: 'romance', order: 18 },
    { title: 'The Elite', author: 'Kiera Cass', language: 'Английский', pages: 323, difficulty: 'B1+', genre: 'romance', order: 19 },
    { title: 'The One', author: 'Kiera Cass', language: 'Английский', pages: 323, difficulty: 'B1+', genre: 'romance', order: 20 },
    { title: 'The Heir', author: 'Kiera Cass', language: 'Английский', pages: 342, difficulty: 'B1+', genre: 'romance', order: 21 },
    { title: 'The Crown', author: 'Kiera Cass', language: 'Английский', pages: 278, difficulty: 'B1+', genre: 'romance', order: 22 },
    { title: 'The Lightning Thief', author: 'Rick Riordan', language: 'Английский', pages: 377, difficulty: 'B1+', genre: 'fantasy', order: 23 },
    { title: 'The Sea of Monsters', author: 'Rick Riordan', language: 'Английский', pages: 279, difficulty: 'B1+', genre: 'fantasy', order: 24 },
    { title: 'The Titan\'s Curse', author: 'Rick Riordan', language: 'Английский', pages: 312, difficulty: 'B1+', genre: 'fantasy', order: 25 },
    { title: 'The Battle of the Labyrinth', author: 'Rick Riordan', language: 'Английский', pages: 361, difficulty: 'B1+', genre: 'fantasy', order: 26 },
    { title: 'The Last Olympian', author: 'Rick Riordan', language: 'Английский', pages: 381, difficulty: 'B1+', genre: 'fantasy', order: 27 },
    { title: 'The Naturals', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 336, difficulty: 'B1+', genre: 'thriller', order: 28 },
    { title: 'Killer Instinct', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 336, difficulty: 'B1+', genre: 'thriller', order: 29 },
    { title: 'All In', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 352, difficulty: 'B1+', genre: 'thriller', order: 30 },
    { title: 'Bad Blood', author: 'Jennifer Lynn Barnes', language: 'Английский', pages: 352, difficulty: 'B1+', genre: 'thriller', order: 31 },
    { title: 'All Systems Red', author: 'Martha Wells', language: 'Английский', pages: 144, difficulty: 'B1+', genre: 'scifi', order: 32 },
    { title: 'Artificial Condition', author: 'Martha Wells', language: 'Английский', pages: 160, difficulty: 'B1+', genre: 'scifi', order: 33 },
    { title: 'Rogue Protocol', author: 'Martha Wells', language: 'Английский', pages: 160, difficulty: 'B1+', genre: 'scifi', order: 34 },
    { title: 'Exit Strategy', author: 'Martha Wells', language: 'Английский', pages: 176, difficulty: 'B1+', genre: 'scifi', order: 35 },
    { title: 'Network Effect', author: 'Martha Wells', language: 'Английский', pages: 352, difficulty: 'B1+', genre: 'scifi', order: 36 },
    { title: 'Fugitive Telemetry', author: 'Martha Wells', language: 'Английский', pages: 176, difficulty: 'B1+', genre: 'scifi', order: 37 },
    { title: 'System Collapse', author: 'Martha Wells', language: 'Английский', pages: 245, difficulty: 'B1+', genre: 'scifi', order: 38 },
    { title: 'Divergent', author: 'Veronica Roth', language: 'Английский', pages: 487, difficulty: 'B2', genre: 'dystopia', order: 39 },
    { title: 'Insurgent', author: 'Veronica Roth', language: 'Английский', pages: 525, difficulty: 'B2', genre: 'dystopia', order: 40 },
    { title: 'Allegiant', author: 'Veronica Roth', language: 'Английский', pages: 526, difficulty: 'B2', genre: 'dystopia', order: 41 },
    { title: 'Four', author: 'Veronica Roth', language: 'Английский', pages: 302, difficulty: 'B2', genre: 'dystopia', order: 42 },
    { title: 'A Court of Thorns and Roses', author: 'Sarah J. Maas', language: 'Английский', pages: 419, difficulty: 'B2', genre: 'fantasy', order: 43 },
    { title: 'A Court of Mist and Fury', author: 'Sarah J. Maas', language: 'Английский', pages: 624, difficulty: 'B2', genre: 'fantasy', order: 44 },
    { title: 'A Court of Wings and Ruin', author: 'Sarah J. Maas', language: 'Английский', pages: 699, difficulty: 'B2', genre: 'fantasy', order: 45 },
    { title: 'A Court of Frost and Starlight', author: 'Sarah J. Maas', language: 'Английский', pages: 288, difficulty: 'B2', genre: 'fantasy', order: 46 },
    { title: 'A Court of Silver Flames', author: 'Sarah J. Maas', language: 'Английский', pages: 757, difficulty: 'B2', genre: 'fantasy', order: 47 },
    { title: 'Storm Front', author: 'Jim Butcher', language: 'Английский', pages: 322, difficulty: 'B2', genre: 'fantasy', order: 48 },
    { title: 'Fool Moon', author: 'Jim Butcher', language: 'Английский', pages: 367, difficulty: 'B2', genre: 'fantasy', order: 49 },
    { title: 'Grave Peril', author: 'Jim Butcher', language: 'Английский', pages: 421, difficulty: 'B2', genre: 'fantasy', order: 50 },
    { title: 'Summer Knight', author: 'Jim Butcher', language: 'Английский', pages: 405, difficulty: 'B2', genre: 'fantasy', order: 51 },
    { title: 'Death Masks', author: 'Jim Butcher', language: 'Английский', pages: 449, difficulty: 'B2', genre: 'fantasy', order: 52 },
    { title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', language: 'Английский', pages: 465, difficulty: 'B2', genre: 'thriller', order: 53 },
    { title: 'The Girl Who Played with Fire', author: 'Stieg Larsson', language: 'Английский', pages: 503, difficulty: 'B2', genre: 'thriller', order: 54 },
    { title: 'The Girl Who Kicked the Hornets\' Nest', author: 'Stieg Larsson', language: 'Английский', pages: 563, difficulty: 'B2', genre: 'thriller', order: 55 },
    { title: 'The Girl in the Spider\'s Web', author: 'David Lagercrantz', language: 'Английский', pages: 400, difficulty: 'B2', genre: 'thriller', order: 56 },
    { title: 'The Girl Who Takes an Eye for an Eye', author: 'David Lagercrantz', language: 'Английский', pages: 496, difficulty: 'B2', genre: 'thriller', order: 57 },
    { title: 'The Girl Who Lived Twice', author: 'David Lagercrantz', language: 'Английский', pages: 384, difficulty: 'B2', genre: 'thriller', order: 58 },
    { title: 'The Girl in the Eagle\'s Talons', author: 'Karin Smirnoff', language: 'Английский', pages: 352, difficulty: 'B2', genre: 'thriller', order: 59 },
    { title: 'Red Rising', author: 'Pierce Brown', language: 'Английский', pages: 382, difficulty: 'B2', genre: 'scifi', order: 60 },
    { title: 'Golden Son', author: 'Pierce Brown', language: 'Английский', pages: 443, difficulty: 'B2', genre: 'scifi', order: 61 },
    { title: 'Morning Star', author: 'Pierce Brown', language: 'Английский', pages: 517, difficulty: 'B2', genre: 'scifi', order: 62 },
    { title: 'Iron Gold', author: 'Pierce Brown', language: 'Английский', pages: 596, difficulty: 'B2', genre: 'scifi', order: 63 },
    { title: 'Dark Age', author: 'Pierce Brown', language: 'Английский', pages: 704, difficulty: 'B2', genre: 'scifi', order: 64 },
    { title: 'Light Bringer', author: 'Pierce Brown', language: 'Английский', pages: 704, difficulty: 'B2', genre: 'scifi', order: 65 },
    { title: 'A Study in Scarlet', author: 'Arthur Conan Doyle', language: 'Английский', pages: 154, difficulty: 'B2+', genre: 'detective', order: 66 },
    { title: 'The Sign of Four', author: 'Arthur Conan Doyle', language: 'Английский', pages: 180, difficulty: 'B2+', genre: 'detective', order: 67 },
    { title: 'The Hound of the Baskervilles', author: 'Arthur Conan Doyle', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 68 },
    { title: 'The Valley of Fear', author: 'Arthur Conan Doyle', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 69 },
    { title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', language: 'Английский', pages: 307, difficulty: 'B2+', genre: 'detective', order: 70 },
    { title: 'The Memoirs of Sherlock Holmes', author: 'Arthur Conan Doyle', language: 'Английский', pages: 280, difficulty: 'B2+', genre: 'detective', order: 71 },
    { title: 'The Return of Sherlock Holmes', author: 'Arthur Conan Doyle', language: 'Английский', pages: 320, difficulty: 'B2+', genre: 'detective', order: 72 },
    { title: 'The Mysterious Affair at Styles', author: 'Agatha Christie', language: 'Английский', pages: 296, difficulty: 'B2+', genre: 'detective', order: 73 },
    { title: 'The Murder of Roger Ackroyd', author: 'Agatha Christie', language: 'Английский', pages: 288, difficulty: 'B2+', genre: 'detective', order: 74 },
    { title: 'Murder on the Orient Express', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 75 },
    { title: 'Death on the Nile', author: 'Agatha Christie', language: 'Английский', pages: 288, difficulty: 'B2+', genre: 'detective', order: 76 },
    { title: 'Cards on the Table', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 77 },
    { title: 'Five Little Pigs', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 78 },
    { title: 'Evil Under the Sun', author: 'Agatha Christie', language: 'Английский', pages: 256, difficulty: 'B2+', genre: 'detective', order: 79 },
    { title: 'Curtain', author: 'Agatha Christie', language: 'Английский', pages: 240, difficulty: 'B2+', genre: 'detective', order: 80 },
    { title: 'The Fellowship of the Ring', author: 'J. R. R. Tolkien', language: 'Английский', pages: 423, difficulty: 'B2+', genre: 'fantasy', order: 81 },
    { title: 'The Two Towers', author: 'J. R. R. Tolkien', language: 'Английский', pages: 352, difficulty: 'B2+', genre: 'fantasy', order: 82 },
    { title: 'The Return of the King', author: 'J. R. R. Tolkien', language: 'Английский', pages: 416, difficulty: 'B2+', genre: 'fantasy', order: 83 },
    { title: 'Leviathan Wakes', author: 'James S. A. Corey', language: 'Английский', pages: 561, difficulty: 'B2+', genre: 'scifi', order: 84 },
    { title: 'Caliban\'s War', author: 'James S. A. Corey', language: 'Английский', pages: 595, difficulty: 'B2+', genre: 'scifi', order: 85 },
    { title: 'Abaddon\'s Gate', author: 'James S. A. Corey', language: 'Английский', pages: 539, difficulty: 'B2+', genre: 'scifi', order: 86 },
    { title: 'Wool', author: 'Hugh Howey', language: 'Английский', pages: 571, difficulty: 'B2+', genre: 'dystopia', order: 87 },
    { title: 'Shift', author: 'Hugh Howey', language: 'Английский', pages: 594, difficulty: 'B2+', genre: 'dystopia', order: 88 },
    { title: 'Dust', author: 'Hugh Howey', language: 'Английский', pages: 386, difficulty: 'B2+', genre: 'dystopia', order: 89 },
    { title: 'Guards! Guards!', author: 'Terry Pratchett', language: 'Английский', pages: 288, difficulty: 'C1', genre: 'fantasy', order: 90 },
    { title: 'Men at Arms', author: 'Terry Pratchett', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 91 },
    { title: 'Feet of Clay', author: 'Terry Pratchett', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 92 },
    { title: 'Jingo', author: 'Terry Pratchett', language: 'Английский', pages: 384, difficulty: 'C1', genre: 'fantasy', order: 93 },
    { title: 'The Fifth Elephant', author: 'Terry Pratchett', language: 'Английский', pages: 384, difficulty: 'C1', genre: 'fantasy', order: 94 },
    { title: 'Night Watch', author: 'Terry Pratchett', language: 'Английский', pages: 352, difficulty: 'C1', genre: 'fantasy', order: 95 },
    { title: 'Thud!', author: 'Terry Pratchett', language: 'Английский', pages: 384, difficulty: 'C1', genre: 'fantasy', order: 96 },
    { title: 'Snuff', author: 'Terry Pratchett', language: 'Английский', pages: 400, difficulty: 'C1', genre: 'fantasy', order: 97 },
    { title: 'Neverwhere', author: 'Neil Gaiman', language: 'Английский', pages: 370, difficulty: 'C1', genre: 'fantasy', order: 98 },
    { title: 'Stardust', author: 'Neil Gaiman', language: 'Английский', pages: 256, difficulty: 'C1', genre: 'fantasy', order: 99 },
    { title: 'American Gods', author: 'Neil Gaiman', language: 'Английский', pages: 588, difficulty: 'C1', genre: 'fantasy', order: 100 },
    { title: 'Anansi Boys', author: 'Neil Gaiman', language: 'Английский', pages: 336, difficulty: 'C1', genre: 'fantasy', order: 101 },
    { title: 'The Ocean at the End of the Lane', author: 'Neil Gaiman', language: 'Английский', pages: 181, difficulty: 'C1', genre: 'fantasy', order: 102 },
    { title: 'The Eyre Affair', author: 'Jasper Fforde', language: 'Английский', pages: 374, difficulty: 'C1', genre: 'detective', order: 103 },
    { title: 'Lost in a Good Book', author: 'Jasper Fforde', language: 'Английский', pages: 399, difficulty: 'C1', genre: 'detective', order: 104 },
    { title: 'The Well of Lost Plots', author: 'Jasper Fforde', language: 'Английский', pages: 388, difficulty: 'C1', genre: 'detective', order: 105 },
    { title: 'Something Rotten', author: 'Jasper Fforde', language: 'Английский', pages: 394, difficulty: 'C1', genre: 'detective', order: 106 },
    { title: 'First Among Sequels', author: 'Jasper Fforde', language: 'Английский', pages: 366, difficulty: 'C1', genre: 'detective', order: 107 },
    { title: 'One of Our Thursdays Is Missing', author: 'Jasper Fforde', language: 'Английский', pages: 356, difficulty: 'C1', genre: 'detective', order: 108 },
    { title: 'The Woman Who Died a Lot', author: 'Jasper Fforde', language: 'Английский', pages: 356, difficulty: 'C1', genre: 'detective', order: 109 },
    { title: 'Rivers of London', author: 'Ben Aaronovitch', language: 'Английский', pages: 400, difficulty: 'C1', genre: 'fantasy', order: 110 },
    { title: 'Moon Over Soho', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 111 },
    { title: 'Whispers Under Ground', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 112 },
    { title: 'Broken Homes', author: 'Ben Aaronovitch', language: 'Английский', pages: 336, difficulty: 'C1', genre: 'fantasy', order: 113 },
    { title: 'Foxglove Summer', author: 'Ben Aaronovitch', language: 'Английский', pages: 352, difficulty: 'C1', genre: 'fantasy', order: 114 },
    { title: 'The Hanging Tree', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 115 },
    { title: 'Lies Sleeping', author: 'Ben Aaronovitch', language: 'Английский', pages: 400, difficulty: 'C1', genre: 'fantasy', order: 116 },
    { title: 'False Value', author: 'Ben Aaronovitch', language: 'Английский', pages: 368, difficulty: 'C1', genre: 'fantasy', order: 117 },
    { title: 'Amongst Our Weapons', author: 'Ben Aaronovitch', language: 'Английский', pages: 320, difficulty: 'C1', genre: 'fantasy', order: 118 },
    { title: '1984', author: 'George Orwell', language: 'Английский', pages: 328, difficulty: 'C2', genre: 'dystopia', order: 119 },
    { title: 'Brave New World', author: 'Aldous Huxley', language: 'Английский', pages: 288, difficulty: 'C2', genre: 'dystopia', order: 120 },
    { title: 'The Handmaid\'s Tale', author: 'Margaret Atwood', language: 'Английский', pages: 311, difficulty: 'C2', genre: 'dystopia', order: 121 },
    { title: 'Never Let Me Go', author: 'Kazuo Ishiguro', language: 'Английский', pages: 288, difficulty: 'C2', genre: 'drama', order: 122 },
    { title: 'Jonathan Strange & Mr Norrell', author: 'Susanna Clarke', language: 'Английский', pages: 782, difficulty: 'C2', genre: 'fantasy', order: 123 },
    { title: 'Wolf Hall', author: 'Hilary Mantel', language: 'Английский', pages: 653, difficulty: 'C2', genre: 'classic', order: 124 },
  ];
}

export function defaultBooksFor(ownerId) {
  return ownerId === 'kausar' ? defaultKausarBooks() : defaultMamaBooks();
}

// ---- Учиться (дисциплины + хобби) ----
export function defaultMamaSubjects() {
  return [
    { category: 'subject', icon: '📐', name: 'Математика', hours: 6.5, approx: false, platform: 'Stepik', url: 'https://stepik.org/course/181515/promo', order: 1 },
    { category: 'subject', icon: '💰', name: 'Финансы', hours: 15, approx: true, platform: '4Brain', url: 'https://4brain.ru/finance/', order: 2 },
    { category: 'subject', icon: '☪️', name: 'Акыда', hours: 25, approx: true, platform: 'Stepik', url: 'https://stepik.org/course/124579/promo', order: 3 },
    { category: 'subject', icon: '📜', name: 'Фикх', hours: 25, approx: true, platform: 'Stepik', url: 'https://stepik.org/course/134284/promo', order: 4 },
    { category: 'subject', icon: '🧠', name: 'Психология', hours: 20, approx: true, platform: 'Stepik', url: 'https://stepik.org/course/132383/promo', order: 5 },
    { category: 'subject', icon: '🎓', name: 'Педагогика', hours: 20, approx: true, platform: 'Stepik', url: 'https://stepik.org/course/53266/promo', order: 6 },
    { category: 'subject', icon: '🍎', name: 'Нутрициология', hours: 15, approx: true, platform: '4Brain', url: 'https://4brain.ru/nutriciology/', order: 7 },
    { category: 'subject', icon: '🩺', name: 'Медицина (основы)', hours: 36, approx: true, platform: 'Открытое образование', url: 'https://openedu.ru/course/msu/MEDSKILLS/', order: 8 },
  ];
}
export function defaultMamaHobbies() {
  return [
    { category: 'hobby', icon: '🧵', name: 'Вышивание', hours: 5, approx: false, platform: 'Udemy', url: 'https://www.udemy.com/course/hand-embroidery-for-beginners/', order: 1 },
    { category: 'hobby', icon: '✂️', name: 'Шитьё', hours: 5, approx: false, platform: 'Udemy', url: 'https://www.udemy.com/course/beginner-sewing-course/', order: 2 },
    { category: 'hobby', icon: '🎂', name: 'Кондитерские изделия', hours: 6, approx: true, platform: 'Udemy', url: 'https://www.udemy.com/course/special-cake-making/', order: 3 },
    { category: 'hobby', icon: '🧶', name: 'Вязание', hours: 4, approx: false, platform: 'Udemy', url: 'https://www.udemy.com/course/knitting101/', order: 4 },
    { category: 'hobby', icon: '🧘', name: 'Йога', hours: 200, approx: false, platform: 'Yoga Alliance', url: 'https://yogaalliance.org/explore-training-options/', order: 5 },
  ];
}
export function defaultStudyItemsFor(ownerId) {
  if (ownerId === 'kausar') return []; // she'll add her own subjects/hobbies
  return [...defaultMamaSubjects(), ...defaultMamaHobbies()];
}

// ---- Образование ----
export function defaultEducationFor() {
  return []; // nobody has picked concrete programs yet — added manually as they're researched
}

// ---- Профессия ----
export function defaultCareerGoalsFor(ownerId) {
  if (ownerId === 'kausar') return [];
  return [
    { category: 'main', icon: '🧒', name: 'Детский педагог-психолог', order: 1 },
    { category: 'main', icon: '💰', name: 'Семейный финансист', order: 2 },
  ];
}

export function defaultSurahs() {
  return [
    { num: 1, name: 'Аль-Фатиха', ayahs: 7, pages: 1 },
    { num: 2, name: 'Аль-Бакара', ayahs: 286, pages: 48 },
    { num: 3, name: 'Али Имран', ayahs: 200, pages: 27 },
    { num: 4, name: 'Ан-Ниса', ayahs: 176, pages: 29 },
    { num: 5, name: 'Аль-Маида', ayahs: 120, pages: 22 },
    { num: 6, name: 'Аль-Анам', ayahs: 165, pages: 23 },
    { num: 7, name: 'Аль-Араф', ayahs: 206, pages: 26 },
    { num: 8, name: 'Аль-Анфаль', ayahs: 75, pages: 10 },
    { num: 9, name: 'Ат-Тауба', ayahs: 129, pages: 21 },
    { num: 10, name: 'Юнус', ayahs: 109, pages: 13 },
    { num: 11, name: 'Худ', ayahs: 123, pages: 14 },
    { num: 12, name: 'Юсуф', ayahs: 111, pages: 14 },
    { num: 13, name: 'Ар-Раад', ayahs: 43, pages: 6 },
    { num: 14, name: 'Ибрахим', ayahs: 52, pages: 7 },
    { num: 15, name: 'Аль-Хиджр', ayahs: 99, pages: 5 },
    { num: 16, name: 'Ан-Нахль', ayahs: 128, pages: 15 },
    { num: 17, name: 'Аль-Исра', ayahs: 111, pages: 11 },
    { num: 18, name: 'Аль-Кахф', ayahs: 110, pages: 12 },
    { num: 19, name: 'Марьям', ayahs: 98, pages: 7 },
    { num: 20, name: 'Та-Ха', ayahs: 135, pages: 10 },
    { num: 21, name: 'Аль-Анбия', ayahs: 112, pages: 10 },
    { num: 22, name: 'Аль-Хадж', ayahs: 78, pages: 10 },
    { num: 23, name: 'Аль-Муминун', ayahs: 118, pages: 8 },
    { num: 24, name: 'Ан-Нур', ayahs: 64, pages: 9 },
    { num: 25, name: 'Аль-Фуркан', ayahs: 77, pages: 8 },
    { num: 26, name: 'Аш-Шуара', ayahs: 227, pages: 10 },
    { num: 27, name: 'Ан-Намль', ayahs: 93, pages: 8 },
    { num: 28, name: 'Аль-Касас', ayahs: 88, pages: 11 },
    { num: 29, name: 'Аль-Анкабут', ayahs: 69, pages: 8 },
    { num: 30, name: 'Ар-Рум', ayahs: 60, pages: 7 },
    { num: 31, name: 'Лукман', ayahs: 34, pages: 4 },
    { num: 32, name: 'Ас-Саджда', ayahs: 30, pages: 3 },
    { num: 33, name: 'Аль-Ахзаб', ayahs: 73, pages: 10 },
    { num: 34, name: 'Саба', ayahs: 54, pages: 6 },
    { num: 35, name: 'Фатыр', ayahs: 45, pages: 6 },
    { num: 36, name: 'Йа-Син', ayahs: 83, pages: 6 },
    { num: 37, name: 'Ас-Саффат', ayahs: 182, pages: 7 },
    { num: 38, name: 'Сад', ayahs: 88, pages: 5 },
    { num: 39, name: 'Аз-Зумар', ayahs: 75, pages: 9 },
    { num: 40, name: 'Гафир', ayahs: 85, pages: 10 },
    { num: 41, name: 'Фуссылят', ayahs: 54, pages: 6 },
    { num: 42, name: 'Аш-Шура', ayahs: 53, pages: 6 },
    { num: 43, name: 'Аз-Зухруф', ayahs: 89, pages: 7 },
    { num: 44, name: 'Ад-Духан', ayahs: 59, pages: 3 },
    { num: 45, name: 'Аль-Джасия', ayahs: 37, pages: 3 },
    { num: 46, name: 'Аль-Ахкаф', ayahs: 35, pages: 5 },
    { num: 47, name: 'Мухаммад', ayahs: 38, pages: 4 },
    { num: 48, name: 'Аль-Фатх', ayahs: 29, pages: 4 },
    { num: 49, name: 'Аль-Худжурат', ayahs: 18, pages: 3 },
    { num: 50, name: 'Каф', ayahs: 45, pages: 2 },
    { num: 51, name: 'Аз-Зарият', ayahs: 60, pages: 3 },
    { num: 52, name: 'Ат-Тур', ayahs: 49, pages: 3 },
    { num: 53, name: 'Ан-Наджм', ayahs: 62, pages: 2 },
    { num: 54, name: 'Аль-Камар', ayahs: 55, pages: 3 },
    { num: 55, name: 'Ар-Рахман', ayahs: 78, pages: 3 },
    { num: 56, name: 'Аль-Вакиа', ayahs: 96, pages: 3 },
    { num: 57, name: 'Аль-Хадид', ayahs: 29, pages: 5 },
    { num: 58, name: 'Аль-Муджадала', ayahs: 22, pages: 3 },
    { num: 59, name: 'Аль-Хашр', ayahs: 24, pages: 4 },
    { num: 60, name: 'Аль-Мумтахана', ayahs: 13, pages: 2 },
    { num: 61, name: 'Ас-Сафф', ayahs: 14, pages: 2 },
    { num: 62, name: 'Аль-Джума', ayahs: 11, pages: 1 },
    { num: 63, name: 'Аль-Мунафикун', ayahs: 11, pages: 2 },
    { num: 64, name: 'Ат-Тагабун', ayahs: 18, pages: 2 },
    { num: 65, name: 'Ат-Талак', ayahs: 12, pages: 2 },
    { num: 66, name: 'Ат-Тахрим', ayahs: 12, pages: 2 },
    { num: 67, name: 'Аль-Мульк', ayahs: 30, pages: 2 },
    { num: 68, name: 'Аль-Калям', ayahs: 52, pages: 2 },
    { num: 69, name: 'Аль-Хакка', ayahs: 52, pages: 2 },
    { num: 70, name: 'Аль-Мааридж', ayahs: 44, pages: 2 },
    { num: 71, name: 'Нух', ayahs: 28, pages: 2 },
    { num: 72, name: 'Аль-Джинн', ayahs: 28, pages: 2 },
    { num: 73, name: 'Аль-Муззаммиль', ayahs: 20, pages: 1 },
    { num: 74, name: 'Аль-Муддассир', ayahs: 56, pages: 2 },
    { num: 75, name: 'Аль-Кыяма', ayahs: 40, pages: 1 },
    { num: 76, name: 'Аль-Инсан', ayahs: 31, pages: 2 },
    { num: 77, name: 'Аль-Мурсалят', ayahs: 50, pages: 2 },
    { num: 78, name: 'Ан-Наба', ayahs: 40, pages: 1 },
    { num: 79, name: 'Ан-Назиат', ayahs: 46, pages: 2 },
    { num: 80, name: 'Абаса', ayahs: 42, pages: 1 },
    { num: 81, name: 'Ат-Таквир', ayahs: 29, pages: 1 },
    { num: 82, name: 'Аль-Инфитар', ayahs: 19, pages: 1 },
    { num: 83, name: 'Аль-Мутаффифин', ayahs: 36, pages: 2 },
    { num: 84, name: 'Аль-Иншикак', ayahs: 25, pages: 1 },
    { num: 85, name: 'Аль-Бурудж', ayahs: 22, pages: 1 },
    { num: 86, name: 'Ат-Тарик', ayahs: 17, pages: 1 },
    { num: 87, name: 'Аль-Аля', ayahs: 19, pages: 1 },
    { num: 88, name: 'Аль-Гашия', ayahs: 26, pages: 1 },
    { num: 89, name: 'Аль-Фаджр', ayahs: 30, pages: 1 },
    { num: 90, name: 'Аль-Балад', ayahs: 20, pages: 1 },
    { num: 91, name: 'Аш-Шамс', ayahs: 15, pages: 1 },
    { num: 92, name: 'Аль-Лейль', ayahs: 21, pages: 1 },
    { num: 93, name: 'Ад-Духа', ayahs: 11, pages: 1 },
    { num: 94, name: 'Аш-Шарх', ayahs: 8, pages: 1 },
    { num: 95, name: 'Ат-Тин', ayahs: 8, pages: 1 },
    { num: 96, name: 'Аль-Аляк', ayahs: 19, pages: 1 },
    { num: 97, name: 'Аль-Кадр', ayahs: 5, pages: 1 },
    { num: 98, name: 'Аль-Баййина', ayahs: 8, pages: 1 },
    { num: 99, name: 'Аз-Зальзаля', ayahs: 8, pages: 1 },
    { num: 100, name: 'Аль-Адият', ayahs: 11, pages: 1 },
    { num: 101, name: 'Аль-Кариа', ayahs: 11, pages: 1 },
    { num: 102, name: 'Ат-Такасур', ayahs: 8, pages: 1 },
    { num: 103, name: 'Аль-Аср', ayahs: 3, pages: 1 },
    { num: 104, name: 'Аль-Хумаза', ayahs: 9, pages: 1 },
    { num: 105, name: 'Аль-Филь', ayahs: 5, pages: 1 },
    { num: 106, name: 'Курайш', ayahs: 4, pages: 1 },
    { num: 107, name: 'Аль-Маун', ayahs: 7, pages: 1 },
    { num: 108, name: 'Аль-Кяусар', ayahs: 3, pages: 1 },
    { num: 109, name: 'Аль-Кяфирун', ayahs: 6, pages: 1 },
    { num: 110, name: 'Ан-Наср', ayahs: 3, pages: 1 },
    { num: 111, name: 'Аль-Масад', ayahs: 5, pages: 1 },
    { num: 112, name: 'Аль-Ихляс', ayahs: 4, pages: 1 },
    { num: 113, name: 'Аль-Фаляк', ayahs: 5, pages: 1 },
    { num: 114, name: 'Ан-Нас', ayahs: 6, pages: 1 },
  ];
}
